#!/bin/sh
queryy=$(printf "%s" "$*")
query="$(echo $query)"
if [[$query == *"gruv"* ]] ; then
    wallpaper=$(/bin/ls $HOME/.config/dwm_config/DWM-Wallpaper-Color-Theme/wallpaper/gruv | sort -R | head -n 1) && path="$HOME/.config/dwm_config/DWM-Wallpaper-Color-Theme/wallpaper/gruv/" && wallpaper_path=$path$wallpaper
    wal -i $wallpaper_path
    wal --theme $queryy
    path_to_config="/home/jeff/.config/dwm_config/DWM-Wallpaper-Color-Theme"
    $(cd $path_to_config/dwm/ && sudo make clean install>/dev/null)
    $(cd $path_to_config/st/ && sudo make clean install>/dev/null)
    $(cd $path_to_config/dmenu/ && sudo make clean install>/dev/null)
    zathura_color=$(exec genzathurarc > /home/jeff/.config/zathura/zathurarc)
elif [[$query == *"nord"*]] ; then
    wallpaper=$(/bin/ls $HOME/.config/dwm_config/DWM-Wallpaper-Color-Theme/wallpaper/nord | sort -R | head -n 1) && path="$HOME/.config/dwm_config/DWM-Wallpaper-Color-Theme/wallpaper/nord/" && wallpaper_path=$path$wallpaper
    wal -i $wallpaper_path
    wal --theme $queryy
    path_to_config="/home/jeff/.config/dwm_config/DWM-Wallpaper-Color-Theme"
    $(cd $path_to_config/dwm/ && sudo make clean install>/dev/null)
    $(cd $path_to_config/st/ && sudo make clean install>/dev/null)
    $(cd $path_to_config/dmenu/ && sudo make clean install>/dev/null)
    zathura_color=$(exec genzathurarc > /home/jeff/.config/zathura/zathurarc)
else 
    wal --theme $query
    path_to_config="/home/jeff/.config/dwm_config/DWM-Wallpaper-Color-Theme"
    $(cd $path_to_config/dwm/ && sudo make clean install>/dev/null)
    $(cd $path_to_config/st/ && sudo make clean install>/dev/null)
    $(cd $path_to_config/dmenu/ && sudo make clean install>/dev/null)
    zathura_color=$(exec genzathurarc > /home/jeff/.config/zathura/zathurarc)
fi
